[user]
name = test
hash = UiB7R3C-B2HoepDBLhnKJ9zHYF1BKAwJQwyzeyT4xiAkQaIBIGepVBoZ4-po97GqlC9gQ_gGuD5nfYyenMi6VIPyFRHA8gEMUAOgAYAC8AEEwAIg

[scopes]
systemd:create
systemd:list
systemd:**:*
containers:list

