syntax = "proto3";

package server.api.auth.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/kheina/openconman/src/gen/srv/api/auth;auth";

service Auth {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_tag) = {
    name: "Auth Service"
    description: "description"
  };

  rpc Login(PostLoginRequest) returns (PostLoginResponse) {
    option (google.api.http) = {
      post: "/v1/user/login"
      body: "*"
      response_body: "*"
    };
  }
}

message PostLoginRequest {
  string username = 10;
  string password = 20;
  repeated string scopes = 30;
}

message PostLoginResponse {
  string token = 10;
  google.protobuf.Timestamp expires = 20;
}
