syntax = "proto3";

package server.api.docker.v1;

import "services/pbs/api/container.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "github.com/kheina/openconman/src/gen/srv/api/docker;docker";

service Container {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_tag) = {
    name: "Docker Service"
    description: "description"
  };

  rpc GetContainers(GetContainerStatusesRequest)
      returns (GetContainerStatusesResponse) {
    option (google.api.http) = {
      get: "/v1/containers"
    };
  }
}

message GetContainerStatusesRequest {}

message GetContainerStatusesResponse {
  repeated server.api.pbs.v1.containers.Container items = 10;
}
