syntax = "proto3";

package server.api.systemd.v1;

import "services/pbs/api/systemd.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "github.com/kheina/openconman/src/gen/srv/api/systemd;systemd";

service Systemd {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_tag) = {
    name: "Systemd Service"
    description: "description"
  };

  rpc ListServices(GetServiceStatusesRequest)
      returns (GetServiceStatusesResponse) {
    option (google.api.http) = {
      get: "/v1/services"
    };
  }

  rpc ListAllServices(GetServiceStatusesRequest)
      returns (GetServiceStatusesResponse) {
    option (google.api.http) = {
      get: "/v1/services/all"
    };
  }

  rpc PutServiceAlias(PutServiceAliasRequest)
      returns (PutServiceAliasResponse) {
    option (google.api.http) = {
      put: "/v1/service/alias"
      body: "*"
      response_body: "item"
    };
  }

  rpc DeleteServiceAlias(DeleteServiceRequest) returns (DeleteServiceResponse) {
    option (google.api.http) = {
      delete: "/v1/service/alias/{name}"
    };
  }

  rpc PutService(PutServiceRequest) returns (PutServiceResponse) {
    option (google.api.http) = {
      put: "/v1/service"
      body: "*"
      response_body: "item"
    };
  }

  rpc DeleteService(DeleteServiceRequest) returns (DeleteServiceResponse) {
    option (google.api.http) = {
      delete: "/v1/service/{name}"
    };
  }

  rpc EnableService(GetEnableServiceRequest) returns (GetServiceResponse) {
    option (google.api.http) = {
      get: "/v1/service/enable/{name}"
    };
  }

  rpc DisableService(GetEnableServiceRequest) returns (GetServiceResponse) {
    option (google.api.http) = {
      get: "/v1/service/disable/{name}"
    };
  }

  rpc GetServiceLogs(GetServiceLogsRequest)
      returns (stream GetServiceLogsResponse) {
    option (google.api.http) = {
      get: "/v1/service/logs/{name}"
    };
  }

  rpc GetService(GetServiceRequest) returns (stream GetServiceResponse) {
    option (google.api.http) = {
      get: "/v1/service/{name}"
    };
  }
}

message GetServiceStatusesRequest {}

message GetServiceStatusesResponse {
  repeated server.api.pbs.v1.systemd.UnitStatus items = 10;
}

message GetEnableServiceRequest {
  // The primary unit name as string
  string name = 10;
}

message GetServiceRequest {
  // The primary unit name as string
  string name = 10;
  // Should the connection stay open and send updates on the status of the
  // service over the same connection
  bool live = 20;
}

message GetServiceResponse {
  server.api.pbs.v1.systemd.UnitStatus item = 10;
}

message PutServiceAliasRequest {
  // The primary unit name as string
  string name = 10;
}

message PutServiceAliasResponse {
  server.api.pbs.v1.systemd.UnitStatus item = 10;
}

message DeleteServiceRequest {
  // The primary unit name as string
  string name = 10;
}

message DeleteServiceResponse {}

message PutServiceRequest {
  // The primary unit name as string
  string name = 10;
  // The contents of the file to be created
  string content = 20;
}

message PutServiceResponse {
  server.api.pbs.v1.systemd.UnitStatus item = 10;
}

message GetServiceLogsRequest {
  // The primary unit name as a string
  string name = 10;
  // How many log messages to retrieve
  optional uint32 lines = 20;
  // Seeks to a concrete journal cursor before iterating and returning messages
  optional string seek = 30;
  // Should the connection stay open and send updates on the status of the
  // service over the same connection. Defaults to false, seek must be nil.
  optional bool live = 40;
}

message LogEntry {
  uint64 timestamp = 10;
  string cursor = 20;
  map<string, string> fields = 30;
}

message GetServiceLogsResponse {
  string name = 10;
  repeated LogEntry logs = 20;
}
